### ISSUE TITLE
Meet with Forecaster and review Morecast

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#1054]
**Describe the task**
meet with 2 or more forecasters ad review how they use Morecast now, and how they use the forecast accuracy map tool.

**Acceptance Criteria**
- [x] met with 2 or more forecasters
- [x] document observations and finding that can be actionable to improve Morecast for the users
- [x] add any relevant tickets to the backlog (new issues)

**SME/User Contact**
Forecasters MM, JE, BS

**Additional context**
- any additional details that could not be captured above

**Comment by tessmgood** [comment]
Forecaster questions: 
- what is the optimal way to communicate bugs and questions? (who, where) 
- what stage is MoreCast at? (complete?)
- where do future visions for the product fit into the roadmap?

**Comment by tessmgood** [comment]
Tracking themes (need more info - usability testing topics):
- table design 
-- abiility to see 24 hours without scrolling 
-- model, forecast, observed side by side w/ time steps: consecutive next days
-- hourlies vs. dalies 
--- when forecasting you want last 3 days worth of dailies 
- station grouping 
-- don't forecast for all stations (coastal, MM)
- smoother interactions (less clicks and mouse movement)
-- keyboard vs mouse (tabbing, enter) 
-- ideation: instead of 'select station' have 'get weather data' or 'add more' (primary/secondary buttons)
