### ISSUE TITLE
Allison Pass - no new observations

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#1059]
**Describe the Bug**
Allison Pass isn't getting new observations!

https://psu.nrs.gov.bc.ca/morecast?codes=317

What other stations are we also missing?

**Comment by andrea-williams** [comment]
I ran this query

`select distinct on (station_code) station_code, weather_date, created_at from hourly_actuals order by station_code, created_at desc;`

against our prod DB and found that these station codes are missing observation data for the last while (the length varies, but it predominantly seems that June 7 2021 was when something changed and we stopped pulling data):

11, 75, 93, 113, 126, 129, 167, 262, 294, 317, 321, 331, 343, 344, 385, 438, 440, 444, 503, 944, 956, 1066, 1289, 1348, 1349, 1350, 1387

(Oh dear. That's a lot of stations!)

**Comment by andrea-williams** [comment]
Logs for the hourly_actuals cronjob show that the data for these stations aren't being written to our DB because the WFWX API is returning a value of `observation_valid = False`. For Alison Pass and a number of other stations, the `observation_valid_comment` shows an error message "barometric pressure must be greater than or equal to 800". I don't believe we use barometric pressure for anything, so I don't think that's necessarily relevant to us.

For other stations, the error message indicates that one of temperature, wind speed, or precipitation is null, and so the observation has been marked as invalid. These values are relevant to us, but I'm not sure if our current business logic that the entire observation should be thrown out because one value is missing is correct.

**Comment by andrea-williams** [comment]
I've chatted with WFWX - the `observation_valid_comment` should include ALL error messages for an observation (so if 2 values are invalid, there should be 2 statements within the comment field indicating such).

@tessmgood to follow up with the forecasters to determine how they'd like invalid observations to be handled by us.

**Comment by tessmgood** [comment]
Chatted with JE and MM — they're accustomed to working with incomplete weather data due to these observation errors/gaps. "Some data is always better than no data".

Optimal solution: display the data that is available and communicate any error(s) in the interface. 
*Barometric errors can be ignored and do not need to be communicated. 

For example, if `observation_valid_comment` = `the value for wind speed cannot be null` please display temp, RH, precip data and display an error for wind (UX x Dev to brainstorm front-end options?).

**Comment by andrea-williams** [comment]
As discussed in stand-up, this ticket only covers the bugfix - i.e., storing observations in our DB even if data is invalid.

The user story to add a FE feature for displaying the error messages received from WFWX API is addressed in #1075
