### ISSUE TITLE
multi-select weather stations on Fire behaviour advisory calc

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#1092]
**As a** *FBAN/Forecaster* **I want** *to be able to select multiple stations  and book mark the selected stations* **So That** *I can save the stations in an area, and easily select 15-30ish stations*

**Additional Context**
- select multiple stations at once
-- some users are likely to set up multiple lists of stations (by zone, by fuel type, etc)
-- some users are deployed to different locations throughout the fire season so we can't consider the list building a one-time task 

**Acceptance Criteria**
- [ ] Given (Context), When I book mark the page, Then the weatherstations selected are captured as a part of the bookmark
- [ ] Given (Context), When I open the weather station dropdown, Then I can select multiple stations by clicking on their station name
- [ ] Given (Context), When I open the weather station dropdown, Then I can type to filter the stations so that it is easy/fast to locate my desired stations (usabililty)
- [ ] Given (Context), If I make a mistake when adding a station, Then I can select that (or many) row(s) and delete them to reverse my mistake. The 'remove stations' button should be disabled until 1+ row is selected

**Progress**
- [x] station, fuel type, grass cure % can be parsed from URL query params and displayed in the table
- [x] multiple stations can be added to the table
- [x] URL query params dynamically updated
- [x] stations from table hooked up to API and result table displays all calculated station results
- [ ] when i click a button i can clear the selected stations

**Comment by conbrad** [comment]
@andrea-williams pointed out each station selected would have different fuel types and potentially grass cure percentage.

Solution we landed on is to fix the date field and allow the users to add a station configuration box row, for as many stations as they like, and add them to a list. Once they hit the calculate button this will make a request via url params that can be bookmarked and shared.

**Comment by conbrad** [comment]
Planning on using these according components for adding multiple stations: https://material-ui.com/components/accordion/

**Comment by conbrad** [comment]
Currently adding station configurations to a list works, but the state is still singular (only one station is requested for). This is all local and not pushed to the PR branch currently.

**Comment by conbrad** [comment]
Changed approaches after a design chat with @tessmgood. Looking into building out multi select with this: https://material-ui.com/components/data-grid/columns/

It should save us some time and be more user friendly.

**Comment by conbrad** [comment]
Added progress section in the ticket with checkboxes that I'll update from now on.

**Comment by tessmgood** [comment]
Love this so much! UX thoughts for Monday:
- increase width of date input so the label doesn't wrap by default / wondering if the PST-08:00 is critical here 
- make 'remove station(s)' button inactive/disabled until a row(s) is selected - should clarify that interaction a bit 
- make station list searchable/filter as you type (pending patterns available to us) it's a very long list. Some users are likely to set up multiple lists (by zone, by fuel type, etc). Some users are deployed to different locations throughout the fire season so we can't consider the list building a one-time task.  
- since the table is so wide, it would be fantastic to freeze the first 4 columns so that when I scroll L-R to see HFI, the station and fuel type remains visible to me
- related, we should move grass cure column beside fuel type (column #4 to be frozen) - this will make it more consistent and apparent with the 'add station list-builder' above
- is it hard to override the Material UI edit pattern: double click to edit? it's not apparent to me at first - to be tested. Or can we make the field controls persistent/always visible (drop down arrow, stepper?  
- keyboard shortcuts / tabbing: right now, if I add a station, select the weather station, and tab, I land on the calculate button - not fuel type. Can we look at this?
