### ISSUE TITLE
FireBAT Tech debt back end

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#1175]
**Describe the task**
this ticket covers the back end tasks that need to be completed for FireBAT

**Acceptance Criteria**
- [x] consistent naming
- [x] module structure (where the modules are, whats in them) (possible general refactor)
- [x] move date in request to higher level
- [x] remove commented out stuff in github action
- [x] make fuel types enum 
- [x] add unit tests - if missing wind direction from forecast, should still be able to calculate stuff, although there may need to be a larger accepted margin of error for fire size, etc.

** Additional Context **
- The API is currently looking for date in two places, first at the root of the request, then on the station. It has to be changed to only look at the root - and front-end has to make the appropriate adjustments.

**Comment by conbrad** [comment]
I wonder if we should add the date to the query parameters too so that loading a url with stations captures the date -- currently it just sets it to today's date.

**Comment by andrea-williams** [comment]
> I wonder if we should add the date to the query parameters too so that loading a url with stations captures the date -- currently it just sets it to today's date.

there's 2 sides to that: easier to share results for a specific date with another user, but then also means that everyone's bookmarks are going to be less useful, because they're going to have to manually set the new date every day

**Comment by Sybrand** [comment]
> > I wonder if we should add the date to the query parameters too so that loading a url with stations captures the date -- currently it just sets it to today's date.
> 
> there's 2 sides to that: easier to share results for a specific date with another user, but then also means that everyone's bookmarks are going to be less useful, because they're going to have to manually set the new date every day

I think that's a big deal - seems to make sense to me to not have the date in. So whenever I go there, it's always up to date.

**Comment by andrea-williams** [comment]
- Getting errors in test_fba_error_random_sample -> CFFDRS _DISTtcalc. Int overflow error (repeatedly). Logs show comment "# TODO: test value is not too large for R's ints" which doesn't appear to be from our codebase. The int value is a very large negative number - I don't know where it's coming from, unless it's just a randomly generated number?
- Getting a bunch of failures on assert status code 422 == 200. Don't know the cause and also don't know how to tell which test cases are failing - output is just assigning random numbers to the json files instead of printing their actual filenames.
