### ISSUE TITLE
Import daily modeled weather data for selected weather stations

### ISSUE THREAD

**Issue by bradyholliday** [bcgov/wps#129]
**As a** *Meteorologist or Fire Behaviour Analyst* **I want** *to be able to import modelled forecast weather data into the Fire Weather Calculator* **So That** *I can generate predicted HFI values for use in preparedness planning*

**Additional Context**
- Import weather from Spot Wx https://spotwx.com/ or Environment & Climate Change Canada (ECCC)
- Limited to GDPS model
- fields to pull in: Temperature, Relative Humidity, Wind direction, wind speed, precipitation (need daily noon values; in order to calculate FWI Indices) (noon universal time)(Cranbrook is mountain Daylight time)

**Acceptance Criteria**
- [ ] Given I select a weather station(s), When I set date fields, Then forecasted weather data is imported into the calculator for the location
- [ ] Given I select a weather station(s), I import weather data, Then the data is forecasted for the specific location of the selected station(s)
- [ ] time of day values have to be relevant to the location (time zones)

**Comment by Sybrand** [comment]
Numerical Weather Prediction Data for Global Deterministic Prediction System - GDPS - 25km: https://weather.gc.ca/grib/grib2_glb_25km_e.html

Useful site with various links to data: https://weather.gc.ca/model_forecast/model_e.html

**Comment by Sybrand** [comment]
I did some discovery, on branch: https://github.com/bcgov/wps-api/tree/feature/model_data/129

# Approach 1 - import GRIB raster data directly into postgis and do queries on data

I downloaded 10 days of global model grib data for temperature, and imported into postgis using raster2pgsql, then cropped the raster to contain only data from B.C.

Querying all the temperatures for a given coordinate takes 6 seconds on the full set of data and 2 seconds when only looking at the B.C. subset.

This approach would not be sufficient for extracting all the values we want for any given station in real time, but we could pre-extract all the values we need for all our stations and store them.

# Approach 2 - import eveyr temperature/coordinate pair as a record into postgis, and do queries on data.

I started doing this, using eccodes - but did not take it to completion. Iterating through records is possible, but I don't know what the query speeds would be once placed in postgis.

# Going forward

1. Continue with evaluation of Approach #2 (individual records) - if query speeds are fast enough, there would be no need to pre-generate per station, and it would work for any coordinate specified. Approach #2 would be the preferred solution if the query speeds are acceptable.

2. Either of these approaches should work for us, download, importing and transforming the data only takes a few minutes running un-optimized on my personal machine. Either of these approaches could be used to pre-generate data for our stations or with little effort. Both approaches could be optimized for real time if needed (by bucketing data appropriately)

3. The solution currently only runs on my local machine, and work is required to get it to run in a containerized environment. (postgis instance etc.)

**Comment by Kyubinhan** [comment]
Web dev instance: 
https://wps-web-pr-99.pathfinder.gov.bc.ca/fire-weather

**Comment by Sybrand** [comment]
@jowand number of issues with giving noon values:

The global model has values in 3 hour increments, so there is no noon value. Neither for Pacific Standard Time nor for Mountain Standard Time (for PST the closes is 1pm, for MST closest is 11am)

From this, there are a number of issues:
- do we pick closest values, or interpolate between the two closest values?
- if we interpolate, do we need to use a particular algorithm to do so?
- we need a mechanism to establish what time zone a weather station is in.

**Comment by jowand** [comment]
oooh @Sybrand this is a juicy one. Love it!
Let me get back to you on this one.

**Comment by jowand** [comment]
forecasters need to forecast noon values so that the values, when pushed through diurnal curve equations forming CFFDRS, they are as close to accurate as possible as to what will happen on the ground. This makes forecast verification a challenge as the 'noon values' are used to force a curve to match and are not necessarily an accurate noon forecast.

Feedback from the field is so important to learn how to manipulate the diurnal curve to match the specific location.

... to be continued...

**Comment by Sybrand** [comment]
@jowand re. station + timezone lookup: a list of stations and time zones will do for this PR - yes. (going forward we may have to figure out something else)

**Comment by jowand** [comment]
@Sybrand 

ok so if there is a standard way to do an interpolation for noon values, neither Jesse nor I know of it. I will dig into CFFDRS papers and see what I can find.

Something to think about, which I started rambling about in the comment above, is that forecasters need to create noon values that will fit the diurnal curve developed in CFFDRS so that they reflect peak burning values. So rather than interpolate for the noon values, we could re-engineer the peak values back along the diurnal curves.

I will see if I can find information on the diurnal curves but I have a feeling we are going down a rabbit hole. For now, stick with your interpolation and I will make a ticket to investigate the reverse engineering option.

**Comment by Sybrand** [comment]
I'm guessing that diurnal curve is going to be a function of time and location - if that's the case it should be easy to plug in if we get it.
