### ISSUE TITLE
ASA: Implement fire zone units

### ISSUE THREAD

**Issue by nealmcloughlin** [bcgov/wps#3158]
**As a** person issuing or receiving fire behaviour advisories

**I need** the scale of analysis to be fire zone units

**So That** the advisory aligns with current BCWS practices and do not get influenced by disparate geographies like Fraser Zone and Haida Gwaii.

**Acceptance Criteria**
- [x] Zone Units are displayed and labeled on the map as opposed to fire zones.
- [x] Advisory computations are completed based on zone unit boundaries.
- [x] Updated combustible land area by zone unit 
- [x] Updated high hfi table by zone unit

**Additional Context**
- Ideally reference back to April 30, 2023 fire data
- Shapefiles: https://bcgov.sharepoint.com/:f:/r/teams/01324/Shared%20Documents/General/_Fire%20Behaviour%20Products%20(Auto%20Spatial%20Advisory,%20Calculator)/Auto%20Spatial%20Advisory/GIS%20-%20FBA%20Areas/Boundaries?csf=1&web=1&e=H3baoj
**Definition of Done**
https://github.com/bcgov/wps/wiki/Definition-of-Done

**Comment by dgboss** [comment]
List of required front-end changes (not exhaustive):

create new pmtiles layer from shapefile (done)
create new pmtiles layer for zone unit labels based on centroid of polygons (done)
field names in the new pmtiles files differ from the old files, so updating field names in order to access
property values on the front-end is required
No longer using the 'mof fire zone id' field, instead use 'objectid'
Calls to our API using the mof fire zone id will now need to use the objectid
Potentially update interfaces in fbaAPI.ts including FireZone and FireZoneArea

**Comment by dgboss** [comment]
List of required back-end changes:

- Update ShapeTypeEnum to include value of 'fire_zone_unit'
- Drop rows from Shape table (ie. advisory_shapes). Populate Shape table from geojson (derived from the shape file using QGIS). Note that source-Identifier will now be the OBJECTID values.
Alternatively, just add new rows to the Shape table using the OBJECTIDs and new shape type enum value of fire_zone_unit
- rename FireZoneArea schema to FireShapeArea and change mof_fire_zone_id property name to fire_shape_id (front-end work required to match this change when parsing API responses
- rename FireZoneHighHfiAreas to FireShapeHighHfiAreas' and change name of mof_fire_zone_id' property

**Comment by BAAlexK** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BCWS---Agile-PSU-5e321393e038fba5bbe203b8/issues/bcgov/wps/3158?planning-poker) with Zenhub @dgboss @conbrad @brettedw
