### ISSUE TITLE
gather qualitative feedback on 90th percentile calculator

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#395]
**Describe the task**
this task covers the actual contacting of users and gathering of quotes/feedback regarding their experience with our application

**Acceptance Criteria**
- [x] contact users from list
- [x] collect feedback 
- [x] store feedback/quotes
- [x] gauge overall feedback from user groups as a whole (+tive or -tive)
- [x] create an engaging visual to communicate what we have learned from the feedback

**Additional context**
- could use Survey Monkey to get some qualitative feedback
- Or here

Internal staff (Wildfire Prevention Officers):
Andrea Rainey (on mat leave but email her and see what her auto reply says)
Shannon Irvine
Matt Lees
Steve Richburg
Mike Morrow
Michael Aldred
Tony Botica
Dana Hicks

External staff (but still within the Prevention program):
Reg Nolander (Mountain Resorts Branch) Reg.Nolander@gov.bc.ca
Lindsay Vandersteeg (BC Parks - she will probably forward to an appropriate person) Lindsay.Vandesteeg@gov.bc.ca

Contractors: best to ask the WPOs to forward to contractor

**Comment by PrakritiM** [comment]
Contacts shared by Brady/Dana during research:
Consultant-
Tove : tove.pashkowski@gmail.com

BCWS:
Rainey, Andrea FLNR:EX <Andrea.Rainey@gov.bc.ca>;
Irvine, Shannon FLNR:EX <Shannon.Irvine@gov.bc.ca>; 
Duncan, Jessica FLNR:EX <Jessica.Duncan@gov.bc.ca>

**Comment by jowand** [comment]
@PrakritiM I edited the list above. Can you add in the email that people can forward the survey on?

**Comment by PrakritiM** [comment]
Well the survey is a survey monkey thing that stores the responses and creates basic stat visuals like the one here:
![Screen Shot 2020-07-28 at 12.19.22 AM.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/b2b3505f-3e8f-4a68-aa72-949269333cc9)

Is this what you asked about forwarding the survey? Or do you want me to write in the email that they can forward it to people who they think would be likely users of the calculator?

**Comment by jowand** [comment]
I meant to just tell the people we give the survey link to that they can forward it to others in their teams or contractors who are using the calculator.

**Comment by jowand** [comment]
@PrakritiM I added Dana Hicks to the distribution list

**Comment by jakemorr** [comment]
@PrakritiM to reach out to Dana and remind him to push the survey out via the community of practice.

Kelly Osbourne runs the CoP but she is working overtime right now.

**Comment by sidtobias** [comment]
@PrakritiM what can we do to help unblock this or do we just need more time?

**Comment by PrakritiM** [comment]
@sidtobias I have reached out to Dana for help, hoping he will get back to me soon(by today), otherwise a bit of pressure would be required to to get users to give feedback @jakemorr any ideas how this could be done?

**Comment by jakemorr** [comment]
I think we should loop @Ben in to start but we can't force people to do the survey when they are busier with Fire season, we can only hope they have time. we also should think about how we can provide reward or praise to those that do provide feedback beyond a simple thank you, to encourage future engagement.

**Comment by PrakritiM** [comment]
Written feedback:

Interesting.  I like the lay out and ease of use.
I would suggest there be a wind direction attributed to the events on a percentage basis at the very minimum to indicate the way in which these events will impact a community and allow for stratification of the data for predictive outcomes.
 
In my estimation that is a prevention and CWPP generation tool for justifying spending ridiculous amounts of money on plans that are based on highly modified fuels assessments.  The coarse data model supports that sort of thinking and I have read enough reports that reference 90th percentile events as a justification without a refined focus to support the treatments in the wrong spot.
 
My personal use is in this data would be to see how many of these events occur annually for things like ISI as opposed to an aggregate.   I do like the trigger number for ISI events however I would like a probability estimate and general direction to look in the sky.
I personally prefer the data to be captured on the Climatology reports to identify trends in the occurrence of 90th percentile events (time of year we get problematic significant drying, weather changes or cold fronts etc).  Secondly, some wind rose data to support the ability to identify areas of concern is critical to place context in the data. 
 
As you can tell I am a skeptical  person, so before claiming that a 90th percentile event is going to require extensive fuel treatments to the East side of a community because that is where the workable opportunities are, I would require some work to validate that claim.  This sort of data compilation with a lack of context will allow for people to generate some scare tactics on the CWPP front and if we are going to use this data to support a Fire Analysis which is a good thing we should also indicate the probable areas of risk as indicated by the data.
 
The one problem with my idea is that there is a need to recognize the bias inherent in each weather station and that the data may be skewed however I suspect that an analysis from a group of weather forecasters could likely solve that problem.
 
Bit of a rant so may require some phone conversation and I can be available as required.
 
-user.

**Comment by PrakritiM** [comment]
![Screen Shot 2020-08-07 at 12.04.35 AM.png](https://images.zenhubusercontent.com/5e331de62bd28c17a1a7b929/62c46cd0-e29e-4336-95f7-3d98a9e3398d)

**Comment by PrakritiM** [comment]
Feedback visual and Quotes:


https://www.surveymonkey.com/stories/SM-6J85YPHD/
