### ISSUE TITLE
Increase disk size for database

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#396]
**Describe the task**
With all the weather model data we're storing, we're going to run out of space fast. Right now we have 5GB allocated, all of that will probably be used up in only a few months.

**Acceptance Criteria**
- [x] Establish how much disk space we can reasonably request.
- [x] Increase disk size.
- [x] Document how to increase disk size.

**Additional context**
- Once we have a good idea of how much disk space we need, we're going to have to establish a long term strategy for data retention.

**Comment by Sybrand** [comment]
B.t.w. - this seems super easy, I quickly tried it in dev:
1. delete pvc of replica
2. delete the pod
3. create a pvc, of the same name, with the size you want
4. pod will attach once the pvc is available, and re-sync the database from scratch
5. wait until the replica is fully synced - repeat this process, doing the leader last

**Comment by andrea-williams** [comment]
Very rough math for disk space calculations:

- 1 run of Donald generates approx. 7 MB of new day. Donald runs 6 times a day, so 42 MB of new data is generated every day by Donald, with a little more data generated by Bender and Marvin. Call it 45 MB of new data per day.
- our current PVC claim is 5 GB, and the current size of our wps DB is approx 0.5 GB, so we have approx 4.5 GB of free disk space (we actually have slightly less than this, because of postgres/postgis templates). 
- if we're generating 45 MB of new data every day, after approx. 100 days we'll run out of disk space.
- If we increase our PVC claim to 15 GB and maintain the same pace of data generation, we'll run out of disk space in just under a year.

Having a year's worth of free disk space is not that much, but increasing our claim to 15 GB seems reasonable given that we're expected to be on Openshift 4 within a year's time.

**Comment by andrea-williams** [comment]
https://github.com/BCDevOps/StorageMigration/blob/master/MigrationSteps.md

**Comment by andrea-williams** [comment]
Note: when creating a new PVC, the default storageclass is `slow` - this type does not exist, causing the PVC to get stuck in 'Pending' mode forever or until platform services get in touch. Don't use 'slow'.

**Comment by andrea-williams** [comment]
The 3 PVCs for PROD have been increased to 15 GB each. Have chosen to keep the PVCs created for each new PR env at 5 GB each, since it doesn't seem necessary to provision THAT much space for each PR.
