### ISSUE TITLE
forecaster direct comparison to observed values displayed on MoreCast

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#502]
**As** *Hagrid* **I want** *to be able to see exactly how far off I was from the observed values* **So That** * So I may improve my forecasting accuracy in the future*

**Additional Context**
- follow up with JE to help flesh out this feature
- look at SpotWX - tabular view, there's a way to select your columns.

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by WeatherJesse** [comment]
Hello!  This product has had a strong impact on me already!  I want to use it more... potentially every day.   Sy showed me around a bit and I found myself considering the results as I went for a walk in an area that happened to be near one of the weather stations we examined.

I have two additional thoughts on this:

1.  I initially thought - "show me how far off I am on average, say over a month", then I realized I do not want to be swayed off course by some outliers.  In other words, if we do move towards showing an average bias, please maintain the capability to also show the dots in all their gory details.  Another factor is that we often switch forecasters and if I want to improve my skill, I don't want to be affected by another forecaster's work.

2.  Can we save this data (starting from here on out) so that we can build in the ability to look back at a particular date range / weather event to see how the guidance performed?  Other agencies that have done similar work have found that the models often exhibit different biases in different large-scale weather patterns.

**Comment by Sybrand** [comment]
@WeatherJesse re. point #2 - we're currently storing all the model predictions, forecasts and observed values for a particular station, so it will be possible to do the kind of historic comparison you're interested in. (RH and temp only right now, but the rest is coming soon. At some point we'll have to start trimming that data, but we haven't decided yet how many years worth of data it makes sense to keep.

**Comment by WeatherJesse** [comment]
Suggestion:  Save all data for a reasonable amount of time.  If/when this gets too bulky, select a subset of weather stations representing different climatological zones for the historic stuff.
