### ISSUE TITLE
what is a good forecast? what is a bad forecast?

### ISSUE THREAD

**Issue by jakemorr** [bcgov/wps#781]
**Describe the task**
We need to start thinking about how Forecasts can be determined to be good or bad, what is the acceptable variance for each weather variable

i.e how man degrees off can a forecaster's temperature forecast be and the forecast still be valuable, how far off does a forecast need to be for it to be considered harmful or hamper the folks on the ground. without having these ranges decided on by the forecasters and the workers they serve it is difficult to say how "accurate" a forecast.
 
What range are you in for 
an accurate temp forecast is a forecast within X degrees of the observed, an inaccurate forecast is at least X degrees more or X degrees less than the observed. is it better to over forecast or under forecast and how would judging these forecasters inadvertently affect the way forecaster do their job.

other variable to consider and how it is different in determining "accuracy" for each
A good RH forecast (how many % different)
Wind speed and direction 
Precipitation (how many mm off)
Dew Point (WIP)

a Side note, accuracy might not even be what we want to measure but it is our starting point 

**Acceptance Criteria**
- [ ] we have a starting point to declare whether a given Forecast is good or bad for each weather variable forecasted
- [ ] we understand the differences and difficulties in determining the "accuracy" of a forecast
- [ ] we have examined how forecast accuracy is measured in other places/fields

**Additional context**
- Is a Forecast a single day event, or is it the sum of the forecasts made on a given day
- Or here

**Comment by ambroseyau** [comment]
View section under **Mar 17, 2021** on the Miro Board
https://miro.com/app/board/o9J_ktow2OY=/ 


**Additional Context From Jesse - This will also be in the TEAMS UX Folder**
Describe the task
At the most basic level, the BC Wildfire Service is a weather-driven business.  Decisions at the provincial, regional, and local level are made using weather forecast information that is produced by a team of weather forecasters.  The accuracy of these forecasts has never been formally measured.  We need to develop a way to measure the accuracy of weather forecasts, both for the human inputs, as well as for potential future automation.  

Forecast verification is also a very valuable tool for the meteorologists.  They will be better able to improve their work if they have a way to assess past skill.

Each weather element will have different criteria for assessing accuracy.  Each weather element also affects the fire environment in a different way, and so for example, temperature is much less important to ‘get right’ than RH or wind.

- We don’t directly forecast dewpoint, it is derived from temperature & RH.
- For most weather elements a forecast is a single day event tied to a single location and weather element.  For rainfall, though, due to the inherent ‘randomness’ of amounts & coverage, an average value from a grouping of stations would be a better way to assess skill.
